version: '3.8'
services:
  app:
    build: ./app
    stdin_open: true
    tty: true
    depends_on:
      - db
      - controller
    command: ./app
  controller:
    build: ./controller
    depends_on:
      - db
    command: ./controller
    ports:
    - "6543:6543"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sysdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
